### PR TITLE
Implementation of sigmoid activation function.

### PR DESCRIPTION
**Pull request by seba-1511**
Quite simple implementation, using the formula sigmoid(x) = 1/(1 + exp(-x)).

I did not write unit tests for this specific activation, as I was not able to find where they are. (I found the acceptance tests, not the unit ones.) If you point me to their location, I will gladly write them.

### CODE REVIEW

**Comment by arnocandel** [comment]
Tanh === Sigmoid… up to scaling and shifting (which the model can account for trivially with input layer weights *= 2 and bias += 1), there’s no need to add an extra activation function, it might confuse the user.  The results will be the same as with Tanh.

Tanh(x) = 2*sigmoid(2x) - 1

**Comment by seba-1511** [comment]
Thank you for the fast answer !

Indeed they are almost the same and there shouldn't be a big impact when using one or the other. I will close the pull request.

I was thinking that making a more complete model would have been useful, and that was an easy first pull request. I couldn't find an issue tracker or functionalities list that you would want to implement. What would be a task requiring additional programming muscle ?

**Comment by tomkraljevic** [comment]
jira.h2o.ai
search pubdev project

i will make this more prominent in github readme.

**Comment by mmalohlava** [comment]
FYI: The following list contains issues for new h2o contributors: 
https://0xdata.atlassian.net/browse/PUBDEV-512?filter=13600


michal

Dne 4/16/15 v 9:29 PM Tom Kraljevic napsal(a):
> jira.h2o.ai
> search pubdev project
>
> i will make this more prominent in github readme.
>
>

**Comment by seba-1511** [comment]
Thank you !

**Pull request closed without merging**
